services:
  load_data:
    container_name: cnd-load-data
    build: .
    depends_on:
      - neo4j
    command: uv run src/main.py

  neo4j:
    container_name: cnd-neo4j
    image: neo4j
    hostname: neo4j
    ports:
      - "7476:7474"
      - "7689:7687"
    environment:
      NEO4J_AUTH: "neo4j/cloudnative4j"
      NEO4J_PLUGINS: '["apoc"]'
    restart: on-failure
